<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BOND" failures="1" tests="1" name="Default test" time="22.924" errors="0" timestamp="11 Oct 2019 07:06:19 GMT">
  <testcase classname="com.TestCases.Testcase1_Actitime" name="login" time="0.907">
    <failure type="java.io.FileNotFoundException" message="C:\Users\Nehesh Sakpal\eclipse-workspace\ACTITIME_BUILD\src\test\resources\screenShotss\ScreenShot____2019.10.11.12.36.14.png (The system cannot find the path specified)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\Nehesh Sakpal\eclipse-workspace\ACTITIME_BUILD\src\test\resources\screenShotss\ScreenShot____2019.10.11.12.36.14.png (The system cannot find the path specified)
at java.base/java.io.FileOutputStream.open0(Native Method)
at java.base/java.io.FileOutputStream.open(FileOutputStream.java:299)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:238)
at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:188)
at org.openqa.selenium.io.FileHandler.copyFile(FileHandler.java:138)
at org.openqa.selenium.io.FileHandler.copy(FileHandler.java:117)
at com.TESTBASE.Actitime_TestBase.screenShots(Actitime_TestBase.java:109)
at com.TESTBASE.Actitime_TestBase.passLogStatus(Actitime_TestBase.java:140)
at Pages.Actitime_login_page.createAnAccount(Actitime_login_page.java:18)
at com.TestCases.Testcase1_Actitime.login(Testcase1_Actitime.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- Default test -->
